remote_theme: just-the-docs/just-the-docs


color_scheme: dark


back_to_top: true
back_to_top_text: "Back to top"



nav_external_links:
  - title: Github Page
    url: https://github.com/ModernWayz/AI-Project
    
  - title: 360° Viewer
    url: https://renderstuff.com/tools/360-panorama-web-viewer/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    
    
 
